<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_hotel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_hotel by id_place
     */
    function get_tbl_hotel($id_place)
    {
        return $this->db->get_where('tbl_place',array('id_place'=>$id_place))->row_array();
    }
    
    /*
     * Get all tbl_hotel count
     */
    function get_all_tbl_hotel_count()
    {
        $this->db->from('tbl_place');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tbl_hotel
     */
    function get_all_tbl_hotel($params = array())
    {
        $this->db->order_by('id_place', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_place')->result_array();
    }
        
    /*
     * function to add new tbl_hotel
     */
    function add_tbl_hotel($params)
    {
        $this->db->insert('tbl_place',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_hotel
     */
    function update_tbl_hotel($id_place,$params)
    {
        $this->db->where('id_place',$id_place);
        return $this->db->update('tbl_place',$params);
    }
    
    /*
     * function to delete tbl_hotel
     */
    function delete_tbl_hotel($id_place)
    {
        return $this->db->delete('tbl_place',array('id_place'=>$id_place));
    }
}
